src/Web/LMSApp/Areas/Educator/Controllers/AssignmentsController.cs
using LMSApp.Data.Models;
using LMSApp.Data.Models.AssignmentRelated;
using LMSApp.Data.Models.Enums;
using LMSApp.Services.CommonInterfaces;
using LMSApp.Services.Models.Assignments;
using LMSApp.Services.Models.Chart;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LMSApp.Areas.Educator.Controllers
{

    public class AssignmentsController : EducatorBaseController
    {
        private IAssignmentService assignmentService;
        private ICourseService courseService;
        private IEducatorService educatorService;
        private IStudentAssignmentService studentAssignmentService;
        private IUserService userService;
        private UserManager<LMSAppUser> userManager;

        public AssignmentsController(
            IAssignmentService assignmentService,
            ICourseService courseService,
            IEducatorService educatorService,
            IStudentAssignmentService studentAssignmentService,
            IUserService userService,
            UserManager<LMSAppUser> userManager)
        {
            this.assignmentService = assignmentService;
            this.courseService = courseService;
            this.educatorService = educatorService;
            this.studentAssignmentService = studentAssignmentService;
            this.userService = userService;
            this.userManager = userManager;
        }

        private static int BinNumberDefault = 10;

        [HttpGet]
        [Authorize(Roles = "Educator")]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Educator")]
        public async Task<IActionResult> Create(AssignmentCreateBindingModel assignment)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(assignment);
            }

            if (assignment.DateCreated == null)
            {
                assignment.DateCreated = DateTime.Now;
            }

            if (assignment.DueDate != null && assignment.DueDate < assignment.DateCreated)
            {

                TempData["Error"] +=
                    "Error: The due date should be after the assignment create date.";

                return this.View(assignment);
            }

            var assignmentId = await this.assignmentService.CreateAsync(assignment);

            var studentIds = assignment.StudentIds;

            if (studentIds.Contains("all"))
            {
                var students = await this.userService.GetAllStudentsByLecturecise(assignment.LectureciseId);

                studentIds = students.Select(st => st.Id).ToList();
            }

            if (studentIds.Count() > 0)
            {
                var createdAssignment = this.assignmentService.GetByIdOriginal(assignmentId);

                foreach (var studentId in studentIds)
                {
                    if (!createdAssignment.StudentsAssignedTo.Any(s => s.StudentId == studentId))
                    {
                        var studentAssignment = new StudentAssignment()
                        {
                            AssignmentId = createdAssignment.LectureciseId,
                            StudentId = studentId,
                            LectureciseId = createdAssignment.LectureciseId,
                            DueDate = assignment.DueDate,
                            AssignmentStatus = AssignmentStatus.Unfinished,
                            Expired = false,
                            Grade = 0m
                        };

                        createdAssignment.StudentsAssignedTo.Add(studentAssignment);
                    }
                }

                await this.assignmentService.SaveAssignmentsDb();
            }


            //TODO - change redirect to all assignments View when I make it
            return RedirectToAction("CurrentYearLecturecises", "Lecturecises", new { Area = "Educator" });
        }

        //All assignments for the courses of the current educator.
        [HttpGet]
        [Authorize(Roles = "Educator")]
        public async Task<IActionResult> AssignmentsInCourses(AssignmentFilterModel filters = null)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var educatorId = this.educatorService.GetByUserId(user.Id).Id;

            //Should not be possible but ...
            if(educatorId == null)
            {
                return View("../AccessDenied");
            }

            var educatorCoursesIds = this.courseService.GetAllByEducator(educatorId).Select(c => c.Id);

            var assignments = new List<AssignmentListViewModel>();

            foreach (var courseId in educatorCoursesIds)
            {
                var courseAssignments = this.assignmentService.GetByCourseId(courseId);

                if (courseAssignments != null && courseAssignments.Count() > 0)
                {
                    assignments.AddRange(courseAssignments);
                }
            }

            var filteredAssignments = ApplyAssignmentFilters(filters, assignments);

            filteredAssignments = filteredAssignments.OrderByDescending(a => a.DateCreated).ToList();

            return View(filteredAssignments);
        }

        [HttpGet]
        [Authorize(Roles = "Educator")]
        public async Task<IActionResult> StudentAssignmentsManage(string asgnId)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var educatorId = this.educatorService.GetByUserId(user.Id).Id;

            //Should not be possible but ...
            if (educatorId == null)
            {
                return View("../AccessDenied");
            }

            var educatorCoursesIds = this.courseService.GetAllByEducator(educatorId).Select(c => c.Id);

            var assignment = this.assignmentService.GetById(asgnId);

            //If the educator is not involved in the current course.
            if (!educatorCoursesIds.Contains(assignment.CourseId))
            {
                return View("../AccessDenied");
            }
            
            //In order to show some assignment info in the view (not to be editted).
            ViewData["assignmentName"] = assignment.Name;
            ViewData["assignmentCourseHeld"] = assignment.CourseHeld;
            ViewData["assignmentDateCreated"] = assignment.DateCreated;
            ViewData["assignmentMaxGrade"] = assignment.MaxGrade.ToString();

            //var studentAssignments = this.assignmentService.GetStudentAssignmentsById(asgnId);

            var studentAssignments = this.studentAssignmentService.GetStudentAssignmentsById(asgnId);

            return View(studentAssignments);
        }

        [HttpPost]
        [Authorize(Roles = "Educator")]
        public async Task<IActionResult> StudentAssignmentsManage(IList<StudentAssignmentEditViewModel> studentAssignments, string asgnId)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var educatorId = this.educatorService.GetByUserId(user.Id).Id;

            if (studentAssignments.Count() > 0)
            {
                foreach (var studentAssignment in studentAssignments)
                {
                    var assignment = this.studentAssignmentService.GetOriginal(asgnId, studentAssignment.StudentId);

                    assignment.AssignmentStatus = studentAssignment.AssignmentStatus;
                    assignment.DueDate = studentAssignment.DueDate;
                    assignment.GradeComment = studentAssignment.GradeComment;
                    
                    if (assignment.Grade != studentAssignment.Grade)
                    {
                        assignment.Grade = studentAssignment.Grade;
                        assignment.GraderId = educatorId;
                    }
                }

                await this.studentAssignmentService.SaveStudentAssignments();
            }

            return RedirectToAction("StudentAssignmentsManage", new { asgnId = asgnId });
        }

        //Statistics are viewable by any Educator or Admin who knows the assignment Id
        [HttpGet]
        public IActionResult ViewStats(string asgnId, string binNumberStr = null)
        {
            var binNumber = BinNumberDefault;
            if(binNumberStr != null)
            {
                var isParsed = int.TryParse(binNumberStr, out binNumber);

                if (!isParsed)
                {
                    binNumber = BinNumberDefault;
                    TempData["Error"] = "Default bin value is {BinNumberDefault}. Please enter an integer value for the bins!";
                }
            }
            
            var assignment = this.assignmentService.GetById(asgnId);

            var studentAssignments = this.studentAssignmentService.GetStudentAssignmentsById(asgnId);

            var nonZerogrades = studentAssignments.Where(a => a.Grade != 0m).Select(a => a.Grade).ToList();

            var maxGrade = assignment.MaxGrade;

            ViewData["assignmentId"] = asgnId;
            ViewData["assignmentName"] = assignment.Name;
            ViewData["assignmentCourseHeld"] = assignment.CourseHeld;
            ViewData["assignmentDateCreated"] = assignment.DateCreated;
            ViewData["studentsWithAssignment"] = studentAssignments.Count().ToString();
            ViewData["assignmentMaxGrade"] = maxGrade.ToString();
            ViewData["assignmentAverageGrade"] = nonZerogrades.Average().ToString("0.0");
            ViewData["assignmentStDevGrade"] = StandardDeviation(nonZerogrades).ToString("0.0");
            ViewData["gradedStudents"] = nonZerogrades.Count().ToString();
            ViewData["binNumber"] = binNumber.ToString();

            var lstModel = PrepareHistogram(nonZerogrades, maxGrade, binNumber);

src/Web/LMSApp/Areas/Student/Controllers/AssignmentsController.cs
using LMSApp.Data.Models;
using LMSApp.Data.Models.AssignmentRelated;
using LMSApp.Data.Models.Enums;
using LMSApp.Services.CommonInterfaces;
using LMSApp.Services.Models.Assignments;
using LMSApp.Services.Models.Chart;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LMSApp.Areas.Student.Controllers
{

    public class AssignmentsController : StudentBaseController
    {
        private IAssignmentService assignmentService;
        private ICourseService courseService;
        private IEducatorService educatorService;
        private IStudentAssignmentService studentAssignmentService;
        private IUserService userService;
        private UserManager<LMSAppUser> userManager;

        public AssignmentsController(
            IAssignmentService assignmentService,
            ICourseService courseService,
            IEducatorService educatorService,
            IStudentAssignmentService studentAssignmentService,
            IUserService userService,
            UserManager<LMSAppUser> userManager)
        {
            this.assignmentService = assignmentService;
            this.courseService = courseService;
            this.educatorService = educatorService;
            this.studentAssignmentService = studentAssignmentService;
            this.userService = userService;
            this.userManager = userManager;
        }

        //All assignments of the current student.
        [HttpGet]
        public async Task<IActionResult> All(AssignmentFilterModel filters = null)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var userId = user.Id;

            var studentId = this.userService.GetStudentByUserId(userId).Id;

            var assignments = this.studentAssignmentService.GetStudentAssignmentsByStudentId(studentId);

            assignments = assignments.OrderByDescending(a => a.DateCreated).ToList();
            
            if (assignments == null)
            {
                return View(new List<StudentAssignmentStudentViewModel>());
            }

            return View(assignments);
        }

    }
}

src/Web/LMSApp/Controllers/GradeChartViewComponent.cs
using LMSApp.Services.CommonInterfaces;
using LMSApp.Services.Models.Chart;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace LMSApp.Controllers
{
    public class GradeChartViewComponent : ViewComponent
    {

        private IStudentAssignmentService studentAssignmentService;

        public GradeChartViewComponent(IStudentAssignmentService studentAssignmentService)
        {
            this.studentAssignmentService = studentAssignmentService;
        }

        public IViewComponentResult Invoke(string asgnId)
        {
            var studentAssignments = this.studentAssignmentService.GetStudentAssignmentsById(asgnId);

            ViewData["studentsWithAssignment"] = studentAssignments.Count().ToString();

            var binCounts = new int[5] { 0, 0, 0, 0, 0 };

            var gradedStudents = 0;

            foreach (var studentAssignment in studentAssignments)
            {
                if (studentAssignment.Grade > 0m)
                {
                    gradedStudents++;
                    var percent = studentAssignment.Grade / 45;

                    if (percent < 0.2m)
                    {
                        binCounts[0]++;
                    }
                    else if (percent < 0.4m)
                    {
                        binCounts[1]++;
                    }
                    else if (percent < 0.6m)
                    {
                        binCounts[2]++;
                    }
                    else if (percent < 0.8m)
                    {
                        binCounts[3]++;
                    }
                    else
                    {
                        binCounts[4]++;
                    }
                }
            }

            ViewData["gradedStudents"] = gradedStudents.ToString();

            var lstModel = new List<SimpleReportViewModel>();
            var percentage = 0;

            for (int i = 0; i < binCounts.Length; i++)
            {
                percentage += 20;
                lstModel.Add(new SimpleReportViewModel
                {
                    DimensionOne = $"{percentage} %",
                    Quantity = binCounts[i]
                });
            }

            return View("ViewStats", lstModel);
        }
    }
}

src/Web/LMSApp/Areas/Educator/Views/Assignments/AssignmentsInCourses.cshtml
@using LMSApp.Services.Models.Assignments

@model IList<AssignmentListViewModel>


@{
    ViewData["Title"] = "All Assignment in Courses Taught";
}

<h4>@ViewData["Title"]</h4>

<partial name="_AssignmentList" for="@Model" />

src/Web/LMSApp/Areas/Educator/Views/Assignments/StudentAssignmentsManage.cshtml
@using LMSApp.Services.CommonInterfaces
@using LMSApp.Services.Models.Assignments
@using LMSApp.Data.Models.Enums

@model IList<StudentAssignmentEditViewModel>

@inject IEducatorService educatorService

@{
    ViewData["Title"] = "Manage Assignment";
}

<h4>@ViewData["Title"]: @ViewData["assignmentName"]</h4>
<div class="d-flex flex-row col-md-10 justify-content-around">
    <h6>Course: @ViewData["assignmentCourseHeld"]</h6>
    <h6>Date given: @ViewData["assignmentDateCreated"]</h6>
    <h6>Maximum grade: @ViewData["assignmentMaxGrade"]</h6>
</div>
<hr class="hr-custom-dark" />

<div class="row">
    <div>
        <form asp-action="StudentAssignmentsManage" asp-route-asgnId="@Model[0].AssignmentId" method="post" id="edit-student-asgn">

            @{
                if (TempData.ContainsKey("Error"))
                {
                    <div class="text-danger">
                        @TempData["Error"];
                    </div>
                }
            }

            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col" class="text-center">Student</th>
                            <th scope="col" class="text-center">Status</th>
                            <th scope="col" class="text-center">Due</th>
                            <th scope="col" class="text-center">Grade</th>
                            <th scope="col" class="text-center">Comment</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.Count(); i++)
                        {

                            <tr>
                                <td class="text-center font-weight-bold">
                                    @Model[i].StudentInfoView
                                    <div class="form-group ml-2">
                                        @*<label  class="mx-md-2" asp-for="CourseId"></label>*@
                                        <input asp-for="@Model[i].StudentId" class="form-control mx-md-2" id="readolny-courseId"
                                               value="@Model[i].StudentId" readonly hidden />
                                        <span asp-validation-for="@Model[i].StudentId" class="text-danger"></span>
                                    </div>
                                </td>
                                <td class="text-center">
                                    <div class="form-group">
                                        @*<label asp-for="@Model[i].AssignmentStatus"></label>*@
                                        <select asp-for="@Model[i].AssignmentStatus" asp-items="Html.GetEnumSelectList<AssignmentStatus>()"
                                                class="form-control font-weight-bold" value="@Model[i].AssignmentStatus"></select>
                                        <span asp-validation-for="@Model[i].AssignmentStatus" class="text-danger"></span>
                                    </div>
                                </td>
                                <td class="text-center">
                                    <div class="font-weight-bold">
                                        @Model[i].DueDate
                                        Change: <div class="form-group">
                                            @*<label asp-for="@Model[i].DueDate"></label>*@
                                            <input asp-for="@Model[i].DueDate" class="form-control" type="date" />
                                            <span asp-validation-for="@Model[i].DueDate" class="text-danger"></span>
                                        </div>
                                    </div>
                                </td>
                                <td class="text-center">
                                    <div class="form-group">
                                        @*<label asp-for="@Model[i].Grade"></label>*@
                                        <input asp-for="@Model[i].Grade" class="form-control font-weight-bold text-right" value="@Model[i].Grade" />
                                        <span asp-validation-for="@Model[i].Grade" class="text-danger"></span>
                                    </div>
                                </td>
                                <td class="align-content-center">
                                    <div>
                                        <div class="form-group">
                                            @*<label asp-for="@Model[i].GradeComment"></label>*@
                                            <textarea asp-for="@Model[i].GradeComment" class="form-control font-weight-bold" value="@Model[i].GradeComment" rows="2"></textarea>
                                            <span asp-validation-for="@Model[i].GradeComment" class="text-danger"></span>
                                        </div>
                                    </div>
                                </td>

                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-dark btn-d-custom my-md-2" value="Apply Changes" />
                <a class="btn btn-danger mx-sm-1"
                   asp-area="Educator" asp-controller="Assignments" asp-action="ViewStats" asp-route-asgnId="@Model[0].AssignmentId">
                    Show Grade Stats
                </a>

            </div>
        </form>


        @*@await Component.InvokeAsync("GradeChart", new { asgnId = Model[0].AssignmentId });*@
    </div>
</div>

src/Web/LMSApp/Areas/Educator/Views/Assignments/ViewStats.cshtml
@using LMSApp.Services.Models.Chart

@model List<SimpleReportViewModel>

@{
    var XLabels = Newtonsoft.Json.JsonConvert.SerializeObject(Model.Select(x => x.DimensionOne).ToList());
    var YValues = Newtonsoft.Json.JsonConvert.SerializeObject(Model.Select(x => x.Quantity).ToList());
    ViewData["Title"] = "Grade stats for:";
    var label = $"{ViewData["studentsWithAssignment"]} out of {ViewData["gradedStudents"]} students graded.";
}

<h4>@ViewData["Title"]<span class="visible" style="color:#DC3545"> @ViewData["assignmentName"] </span></h4>
<div class="d-flex flex-row col-md-10 justify-content-around">
    <h6>Course: @ViewData["assignmentCourseHeld"]</h6>
    <h6>Date given: @ViewData["assignmentDateCreated"]</h6>
    <h6>Maximum grade: @ViewData["assignmentMaxGrade"]</h6>
</div>

<hr class="hr-custom-dark" />


@{var asgnId = ViewData["assignmentId"];
    var binNumberStr = ViewData["binNumber"];}

<form asp-action="ViewStats" method="get" id="edit-bins" class="form-inline pb-4">

    @{
        if (TempData.ContainsKey("Error"))
        {
            <div class="text-danger">
                @TempData["Error"]
            </div>
        }
    }
    <div class="d-flex flex-row align-items-center">
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group ml-2">
            @*<label  class="mx-md-2" asp-for="CourseId"></label>*@
            <input asp-for="@asgnId" class="form-control mx-md-2" id="readolny-courseId" value="@ViewData["assignmentId"]" readonly hidden />
            <span asp-validation-for="@asgnId" class="text-danger"></span>
            <label class="mx-md-2 font-weight-bold" asp-for="@binNumberStr">Histogram Bins</label>
            <input asp-for="@binNumberStr" class="form-control mx-md-2" value="@binNumberStr" />
            <span asp-validation-for="@binNumberStr" class="text-danger"></span>
        </div>

        <input type="submit" class="btn btn-dark btn-d-custom" value="Change" />
    </div>
</form>

<div class="d-flex flex-row col-md-10 justify-content-around">
    <h6>Students with assignment: <span style="color: #DC3545"> @ViewData["studentsWithAssignment"]</span></h6>
    <h6>Students finished:  <span style="color:#DC3545"> @ViewData["gradedStudents"]</span></h6>
</div>

<div class="d-flex flex-row col-md-10 justify-content-around">
    <h6>Average grade: <span style="color: #DC3545"> @ViewData["assignmentAverageGrade"] </span></h6>
    <h6>Standard deviation: <span style="color: #DC3545"> @ViewData["assignmentStDevGrade"] </span></h6>
</div>


<div class="box-body p-4">

    <div class="chart-container col-10">
        <canvas id="chart" style="width:100%; height:300px"></canvas>
    </div>
</div>

<a class="btn btn-d-custom btn-sm mx-sm-1"
   asp-area="Educator" asp-controller="Assignments" asp-action="StudentAssignmentsManage" asp-route-asgnId="@ViewData["assignmentId"]">
    Back to Assignment
</a>

@section scripts {
    <script type="text/javascript">

        $(function () {
    var chartName = "chart";
        var ctx = document.getElementById(chartName).getContext('2d');
        var data = {
                labels: @Html.Raw(XLabels),
                datasets: [{
                    label: "Number of students",
                    //backgroundColor: 'rgba(220,53,69,0.5)',
                    //backgroundColor: 'rgb(173,216,230)',
                    backgroundColor: 'rgb(52,58,64)',
                    borderColor: 'rgb(52,58,64)',
                    //    [
                    //    'rgba(255, 99, 132, 0.2)',
                    //    'rgba(54, 162, 235, 0.2)',
                    //    'rgba(255, 206, 86, 0.2)',
                    //    'rgba(75, 192, 192, 0.2)',
                    //    'rgba(153, 102, 255, 0.2)',
                    //    'rgba(255, 159, 64, 0.2)',
                    //    'rgba(255, 0, 0)',
                    //    'rgba(0, 255, 0)',
                    //    'rgba(0, 0, 255)',
                    //    'rgba(192, 192, 192)',
                    //    'rgba(255, 255, 0)',
                    //    'rgba(255, 0, 255)'
                    //],
                    //borderColor: [
                    //    'rgba(255,99,132,1)',
                    //    'rgba(54, 162, 235, 1)',
                    //    'rgba(255, 206, 86, 1)',
                    //    'rgba(75, 192, 192, 1)',
                    //    'rgba(153, 102, 255, 1)',
                    //    'rgba(255, 159, 64, 1)',
                    //    'rgba(255, 0, 0)',
                    //    'rgba(0, 255, 0)',
                    //    'rgba(0, 0, 255)',
                    //    'rgba(192, 192, 192)',
                    //    'rgba(255, 255, 0)',
                    //    'rgba(255, 0, 255)'
                    //],
                    scaleFontColor: 'rgba(220,53,69)',
                    borderWidth: 1,
                    data: @Html.Raw(YValues)
    }]
            };

var options = {
                maintainAspectRatio: false,
                scales: {
                    yAxes: [{
                        ticks: {
                            min: 0,
                            fontColor: 'rgba(220, 53, 69)',
                            fontSize: 18,
                            stepSize: 1,
                            beginAtZero: true
                        },
                        gridLines: {
                            display: true,
                            color: "rgba(255,99,164,0.2)"
                        }
}],
                    xAxes: [{
                        ticks: {
                            min: 0,
                            fontColor: 'rgba(220, 53, 69)',
                            fontSize: 18,
                            beginAtZero: true
                        },
                        gridLines: {
                            display: false
                        }
                    }]
                }
            };

       var myChart = new  Chart(ctx, {
                options: options,
                data: data,
                type:'bar'

            });
        });
    </script>
}

src/Web/LMSApp/Areas/Educator/Views/Assignments/_AssignmentList.cshtml
@using LMSApp.Services.Models.Assignments

@model IList<AssignmentListViewModel>
@*@inject UserManager<LMSAppUser> UserManager

    @{var currentUser = await UserManager.GetUserAsync(this.User);}*@

@if (Model.Count() != 0)
{
    <table class="table table-responsive col-12" id="lecturecise-list">
        <thead>
            <tr>
                <th scope="col" class="text-center">Name & Type</th>
                <th scope="col" class="text-center">From</th>
                <th scope="col" class="text-center">Students</th>
                <th scope="col" class="text-center">Course</th>
                <th scope="col" class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var asgn in Model)
            {
                <tr>
                    <td class="text-center">
                        <div class="d-flex flex-column align-items-center">
                            <div>
                                @asgn.Name
                            </div>
                            <div>
                                @asgn.AssignmentType
                            </div>
                        </div>
                    </td>
                    <td class="text-center">
                        @asgn.DateCreated
                    </td>
                    <td class="text-center">
                        @asgn.NumberOfStudents
                    </td>
                    <td class="align-content-center">
                        <div>
                            @asgn.CourseHeld
                        </div>
                    </td>
                    <td class="text-center">
                        <div class="d-flex flex-row  justify-content-center align-items-center">
                            @*<div class="d-flex flex-column justify-content-center align-items-center">
                                    <a class="btn btn-d-custom btn-sm mx-sm-1"
                                       asp-area="Educator" asp-controller="Lecturecises" asp-action="AddStudentsToLecturecise" asp-route-lectureciseId="@lecturecise.Id">
                                        Add Students
                                    </a>
                                </div>*@
                            @*@if (await UserManager.IsInRoleAsync(currentUser, "Admin"))
                                {*@
                            <div class="d-flex flex-column justify-content-center align-items-center">
                                <a class="btn btn-d-custom btn-sm mx-sm-1"
                                   asp-area="Educator" asp-controller="Assignments" asp-action="StudentAssignmentsManage" asp-route-asgnId="@asgn.Id">
                                    Manage & Grade
                                </a>
                            </div>

                            </div>

                            @*<div class="p-md-2">
                                    <a class="btn btn-danger btn-sm mx-sm-1"
                                       asp-area="Admin" asp-controller="Lecturecises" asp-action="Delete" asp-route-lectureciseId="@lecturecise.Id"
                                       onclick="return confirm('Are you sure you wish to remove this Lecturecise?');">
                                        Delete
                                    </a>
                                </div>*@
                            @*}*@
                        
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

src/Web/LMSApp/Areas/Educator/Views/Assignments/_Layout.cshtml
@{ 
    Layout = "/Views/Shared/_Layout.cshtml";
}

<h2>Teaching</h2>

<div>
    <hr class="hr-custom-dark"/>
    <div class="row">
        <div class="col-md-3">
            <partial name="../Courses/_CourseNav" />
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</div>

@section Scripts {
    @RenderSection("Scripts", required: false)
}